<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Jade Anderson" />
    <meta name="description" content="I&#39;m a third year Biology and Sustainability Studies student at the University of Texas at Austin. I love good food, exploring native ecosystems, and R!">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.60.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="modeling" class="section level1">
<h1>Modeling</h1>
<div id="instructions" class="section level2">
<h2>Instructions</h2>
<p>A knitted R Markdown document (as a PDF) and the raw R Markdown file (as .Rmd) should both be submitted to Canvas by 11:59pm on 11/24/2019. These two documents will be graded jointly, so they must be consistent (i.e., don’t change the R Markdown file without also updating the knitted document). Knit an html copy too, for later! In the .Rmd file for Project 2, you can copy the first code-chunk into your project .Rmd file to get better formatting. Notice that you can adjust the opts_chunk$set(…) above to set certain parameters if necessary to make the knitting cleaner (you can globally set the size of all plots, etc). I have gone ahead and set a few for you (such as disabling warnings and package-loading messges when knitting)!</p>
<p>Like before, I envision your written text forming something of a narrative structure around your code/output. All results presented must have corresponding code. Any answers/results/plots etc. given without the corresponding R code that generated the result will not be graded. Furthermore, all code contained in your final project document should work properly. Please do not include any extraneous code or code which produces error messages. (Code which produces warnings is acceptable, as long as you understand what the warnings mean).</p>
</div>
<div id="find-data" class="section level2">
<h2>Find data:</h2>
<p>Find one dataset with at least 5 variables that wish to use to build model. At least one should be categorical (with 2-5 groups) and at least two should be numeric. Ideally, one of your variables will be binary (if not, you will need to create one by discretizing a numeric, which is workable but less than ideal). You will need a minimum of 40 observations (<em>at least</em> 10 observations for every explanatory variable you have, ideally 20+ observations/variable).</p>
<p>It is perfectly fine to use either dataset (or the merged dataset, or a subset of your variables) from Project 1. However, you could also diversify your portfolio a bit by choosing a different dataset to work with (particularly if the variables did not reveal interesting associations in Project 1). The only requirement/restriction is that you may not use data from any examples we have done in class or lab. It would be a good idea to pick more cohesive data this time around (i.e., variables that you actually thing might have a relationship you would want to test). Think more along the lines of your Biostats project.</p>
<p>Again, you can use data from anywhere you want (see bottom for resources)! If you want a quick way to see whether a built-in (R) dataset has binary and/or character (i.e., categorical) variables, check out this list: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
</div>
</div>
<div id="data-writeup" class="section level1">
<h1>Data WriteUp</h1>
<p>The dataset I chose to evaluate consists of Colorado, USA mountain peaks that have an elevation greater than 14,000 feet. Many of these mountains are “fourteeners”, which have peaks higher than 14,000 ft and a prominance at least 300 feet higher than the neighboring peak, although not all of the listed mountains qualify for this label. Each mountain has data specifying a unique ID “ID”, the name of the peak “Mt_Peak”, what mountain range it’s apart of “Mt_Range”, the elevation of the peak (ft) “Elevation_ft”, whether it qualifies as a “fourteener” “fourteener”, the prominence (ft) or how much higher it is from the neighboring peak “Prominence_ft”, the Isolation (mi) or how far it is from a mountain of the same or higher elevation “Isolation_mi”. The data also includes latitude “Lat”, longitude “Long”, the most commonly used hiking route “St_Route”, the distance of the standard route in miles “Distance_mi”, elevation gain of the standard route (ft) “Ele_Gain_ft”, the Yosemite Decimal System difficulty rating “Difficulty”, the low range of estimated visits in 2017 “Low”, and the high range of estimated visits in 2017 “High”.</p>
</div>
<div id="question1" class="section level1">
<h1>Question1</h1>
<pre class="r"><code>library(dplyr)
library(ggplot2)
library(readr)
X14er &lt;- read_csv(&quot;~/Downloads/14er.csv&quot;)
x14&lt;- X14er %&gt;% transmute(ID = ID, Mt_Peak = `Mountain Peak`, Mt_Range=`Mountain Range`, 
                         St_Route =`Standard Route`, Difficulty = Difficulty, Lat = Lat, Long = Long, 
Elevation_ft = Elevation_ft,  Prominence_ft = Prominence_ft, Isolation_mi = Isolation_mi,  Distance_mi = Distance_mi, Ele_Gain_ft = `Elevation Gain_ft`, Low = `Traffic Low`,
High = `Traffic High`, fourteener=as.numeric(fourteener==&quot;Y&quot;,1)) 

ggplot(x14, aes(x = Elevation_ft, y = Isolation_mi)) +
   geom_point(alpha=.5) +geom_density_2d(h=2) +coord_fixed()+facet_wrap(~Mt_Range)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-1-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(x14, aes(x = Prominence_ft, y = Ele_Gain_ft)) +
   geom_point(alpha=.5) +geom_density_2d(h=2) +coord_fixed()+facet_wrap(~Mt_Range)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-1-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(x14, aes(x = High, y = Low)) +
   geom_point(alpha=.5) +geom_density_2d(h=2) +coord_fixed()+facet_wrap(~Mt_Range)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-1-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>covmats&lt;-x14%&gt;%group_by(Mt_Range)%&gt;% do(covs=cov(.[8:14]))
glimpse(for(i in 1:6){print(covmats$covs[i])})</code></pre>
<pre><code>## [[1]]
## Elevation_ft Prominence_ft Isolation_mi Distance_mi
Ele_Gain_ft Low High
## Elevation_ft 8525.6667 61780.33333 643.275000 116.291667
3291.6667 0 0
## Prominence_ft 61780.3333 769265.95238 4918.385238
-41.440476 -7820.2381 0 0
## Isolation_mi 643.2750 4918.38524 53.340824 1.458452
-549.1905 0 0
## Distance_mi 116.2917 -41.44048 1.458452 22.467262
2164.8810 0 0
## Ele_Gain_ft 3291.6667 -7820.23810 -549.190476
2164.880952 232023.8095 0 0
## Low 0.0000 0.00000 0.000000 0.000000 0.0000 0 0
## High 0.0000 0.00000 0.000000 0.000000 0.0000 0 0
##
## [[1]]
## Elevation_ft Prominence_ft Isolation_mi Distance_mi
Ele_Gain_ft Low
## Elevation_ft 9003.900 -19921.00 -306.6080 -287.95000
-73315.00 -318000.00
## Prominence_ft -19921.000 3287656.67 40546.7267
11475.83333 2858516.67 -10846666.67
## Isolation_mi -306.608 40546.73 601.7001 173.13933
45432.67 -132166.67
## Distance_mi -287.950 11475.83 173.1393 61.24167 15835.83
-31333.33
## Ele_Gain_ft -73315.000 2858516.67 45432.6667 15835.83333
4146416.67 -7866666.67
## Low -318000.000 -10846666.67 -132166.6667 -31333.33333
-7866666.67 66666666.67
## High -318000.000 -10846666.67 -132166.6667 -31333.33333
-7866666.67 66666666.67
## High
## Elevation_ft -318000.00
## Prominence_ft -10846666.67
## Isolation_mi -132166.67
## Distance_mi -31333.33
## Ele_Gain_ft -7866666.67
## Low 66666666.67
## High 66666666.67
##
## [[1]]
## Elevation_ft Prominence_ft Isolation_mi Distance_mi
Ele_Gain_ft Low
## Elevation_ft 8442.2667 59222.53 226.82067 50.4000
30113.3333 -78666.6667
## Prominence_ft 59222.5333 1854539.37 11187.38933 937.9500
192896.6667 -383333.3333
## Isolation_mi 226.8207 11187.39 73.15207 5.4045 488.9333
-966.6667
## Distance_mi 50.4000 937.95 5.40450 1.6500 502.5000
2000.0000
## Ele_Gain_ft 30113.3333 192896.67 488.93333 502.5000
262666.6667 616666.6667
## Low -78666.6667 -383333.33 -966.66667 2000.0000
616666.6667 6666666.6667
## High -78666.6667 -383333.33 -966.66667 2000.0000
616666.6667 6666666.6667
## High
## Elevation_ft -78666.6667
## Prominence_ft -383333.3333
## Isolation_mi -966.6667
## Distance_mi 2000.0000
## Ele_Gain_ft 616666.6667
## Low 6666666.6667
## High 6666666.6667
##
## [[1]]
## Elevation_ft Prominence_ft Isolation_mi Distance_mi
Ele_Gain_ft Low
## Elevation_ft 8911.32418 87485.643 1693.49813 -19.43269
-18792.308 -28197.8022
## Prominence_ft 87485.64286 1909390.533 26722.35560
-2013.20192 -930415.385 51978.0220
## Isolation_mi 1693.49813 26722.356 535.45105 -21.98596
-10920.000 942.4176
## Distance_mi -19.43269 -2013.202 -21.98596 19.84375
5307.692 -1692.3077
## Ele_Gain_ft -18792.30769 -930415.385 -10920.00000
5307.69231 1689230.769 -553846.1538
## Low -28197.80220 51978.022 942.41758 -1692.30769
-553846.154 1142857.1429
## High -28197.80220 51978.022 942.41758 -1692.30769
-553846.154 1142857.1429
## High
## Elevation_ft -28197.8022
## Prominence_ft 51978.0220
## Isolation_mi 942.4176
## Distance_mi -1692.3077
## Ele_Gain_ft -553846.1538
## Low 1142857.1429
## High 1142857.1429
##
## [[1]]
## Elevation_ft Prominence_ft Isolation_mi Distance_mi
Ele_Gain_ft Low High
## Elevation_ft 12955.3778 137199.556 2574.47844 201.07222
64253.333 0 0
## Prominence_ft 137199.5556 4224607.389 56456.70278
-1148.54167 -367391.667 0 0
## Isolation_mi 2574.4784 56456.703 1078.40639 25.57997
8123.272 0 0
## Distance_mi 201.0722 -1148.542 25.57997 13.97847
4733.194 0 0
## Ele_Gain_ft 64253.3333 -367391.667 8123.27222 4733.19444
1752472.222 0 0
## Low 0.0000 0.000 0.00000 0.00000 0.000 0 0
## High 0.0000 0.000 0.00000 0.00000 0.000 0 0
##
## [[1]]
## Elevation_ft Prominence_ft Isolation_mi Distance_mi
Ele_Gain_ft Low
## Elevation_ft 20547.5714 159879.8571 10780.13214
136.37500 760.7143 331142.857
## Prominence_ft 159879.8571 4168564.4952 335495.98167
-111.79762 -75504.0476 7778957.143
## Isolation_mi 10780.1321 335495.9817 29397.60670
-42.38315 4711.2738 680422.143
## Distance_mi 136.3750 -111.7976 -42.38315 7.58631
1121.1310 -1696.429
## Ele_Gain_ft 760.7143 -75504.0476 4711.27381 1121.13095
516023.8095 -86428.571
## Low 331142.8571 7778957.1429 680422.14286 -1696.42857
-86428.5714 17114285.714
## High 394285.7143 9273890.4762 809902.61905 -1648.80952
-78809.5238 20300000.000
## High
## Elevation_ft 394285.71
## Prominence_ft 9273890.48
## Isolation_mi 809902.62
## Distance_mi -1648.81
## Ele_Gain_ft -78809.52
## Low 20300000.00
## High 24123809.52
##
## NULL</code></pre>
<pre class="r"><code>man1&lt;- manova(cbind(Elevation_ft, Prominence_ft, Isolation_mi, Distance_mi, Ele_Gain_ft, Low, High)~Mt_Range, data=x14)
summary(man1)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Mt_Range 5 1.8699 4.2672 35 250 5.986e-12 ***
## Residuals 52
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>glimpse(summary.aov(man1))</code></pre>
<pre><code>## List of 7
## $ Response Elevation_ft :Classes &#39;anova&#39; and
&#39;data.frame&#39;: 2 obs. of 5 variables:
## ..$ Df : num [1:2] 5 52
## ..$ Sum Sq : num [1:2] 148714 658496
## ..$ Mean Sq: num [1:2] 29743 12663
## ..$ F value: num [1:2] 2.35 NA
## ..$ Pr(&gt;F) : num [1:2] 0.0537 NA
## $ Response Prominence_ft:Classes &#39;anova&#39; and
&#39;data.frame&#39;: 2 obs. of 5 variables:
## ..$ Df : num [1:2] 5 52
## ..$ Sum Sq : num [1:2] 8.12e+06 1.52e+08
## ..$ Mean Sq: num [1:2] 1624688 2914039
## ..$ F value: num [1:2] 0.558 NA
## ..$ Pr(&gt;F) : num [1:2] 0.732 NA
## $ Response Isolation_mi :Classes &#39;anova&#39; and
&#39;data.frame&#39;: 2 obs. of 5 variables:
## ..$ Df : num [1:2] 5 52
## ..$ Sum Sq : num [1:2] 16333 431927
## ..$ Mean Sq: num [1:2] 3267 8306
## ..$ F value: num [1:2] 0.393 NA
## ..$ Pr(&gt;F) : num [1:2] 0.851 NA
## $ Response Distance_mi :Classes &#39;anova&#39; and
&#39;data.frame&#39;: 2 obs. of 5 variables:
## ..$ Df : num [1:2] 5 52
## ..$ Sum Sq : num [1:2] 310 939
## ..$ Mean Sq: num [1:2] 62.1 18.1
## ..$ F value: num [1:2] 3.44 NA
## ..$ Pr(&gt;F) : num [1:2] 0.0093 NA
## $ Response Ele_Gain_ft :Classes &#39;anova&#39; and
&#39;data.frame&#39;: 2 obs. of 5 variables:
## ..$ Df : num [1:2] 5 52
## ..$ Sum Sq : num [1:2] 31524823 68394143
## ..$ Mean Sq: num [1:2] 6304965 1315272
## ..$ F value: num [1:2] 4.79 NA
## ..$ Pr(&gt;F) : num [1:2] 0.00112 NA
## $ Response Low :Classes &#39;anova&#39; and &#39;data.frame&#39;: 2 obs.
of 5 variables:
## ..$ Df : num [1:2] 5 52
## ..$ Sum Sq : num [1:2] 2.73e+09 6.21e+08
## ..$ Mean Sq: num [1:2] 5.45e+08 1.19e+07
## ..$ F value: num [1:2] 45.6 NA
## ..$ Pr(&gt;F) : num [1:2] 7.61e-18 NA
## $ Response High :Classes &#39;anova&#39; and &#39;data.frame&#39;: 2
obs. of 5 variables:
## ..$ Df : num [1:2] 5 52
## ..$ Sum Sq : num [1:2] 3.72e+09 7.19e+08
## ..$ Mean Sq: num [1:2] 7.45e+08 1.38e+07
## ..$ F value: num [1:2] 53.8 NA
## ..$ Pr(&gt;F) : num [1:2] 2.28e-19 NA
## - attr(*, &quot;class&quot;)= chr [1:2] &quot;summary.aov&quot; &quot;listof&quot;</code></pre>
<pre class="r"><code>x14%&gt;%group_by(Mt_Range)%&gt;%summarize(mean(Elevation_ft), mean(Prominence_ft), mean(Isolation_mi), mean(Distance_mi), mean(Ele_Gain_ft), mean(Low), mean(High))</code></pre>
<pre><code>## # A tibble: 6 x 8
## Mt_Range `mean(Elevation… `mean(Prominenc…
`mean(Isolation… `mean(Distance_… `mean(Ele_Gain_…
## &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Elk Mou… 14111 1396.  5.94 13.7 4907.
## 2 Front R… 14210.  2548.  23.5 11.4 3908.
## 3 Mosquit… 14196.  1179.  6.09 5 2467.
## 4 San Jua… 14096.  1775.  15.2 12.1 4500
## 5 Sangre … 14137.  1996.  17.3 12.5 5105
## 6 Sawatch… 14216 2078.  50.6 10.6 4623.
## # … with 2 more variables: `mean(Low)` &lt;dbl&gt;,
`mean(High)` &lt;dbl&gt;</code></pre>
<pre class="r"><code>glimpse(pairwise.t.test(x14$Elevation_ft, x14$Mt_Range, p.adj=&quot;bonferroni&quot;))</code></pre>
<pre><code>## List of 4
## $ method : chr &quot;t tests with pooled SD&quot;
## $ data.name : chr &quot;x14$Elevation_ft and x14$Mt_Range&quot;
## $ p.value : num [1:5, 1:5] 1 1 1 1 0.699 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:5] &quot;Front Range&quot; &quot;Mosquito Range&quot; &quot;San
Juan Mountains&quot; &quot;Sangre de Cristo Range&quot; ...
## .. ..$ : chr [1:5] &quot;Elk Mountains&quot; &quot;Front Range&quot;
&quot;Mosquito Range&quot; &quot;San Juan Mountains&quot; ...
## $ p.adjust.method: chr &quot;bonferroni&quot;
## - attr(*, &quot;class&quot;)= chr &quot;pairwise.htest&quot;</code></pre>
<pre class="r"><code>glimpse(pairwise.t.test(x14$Prominence_ft, x14$Mt_Range, p.adj=&quot;bonferroni&quot;))</code></pre>
<pre><code>## List of 4
## $ method : chr &quot;t tests with pooled SD&quot;
## $ data.name : chr &quot;x14$Prominence_ft and x14$Mt_Range&quot;
## $ p.value : num [1:5, 1:5] 1 1 1 1 1 NA 1 1 1 1 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:5] &quot;Front Range&quot; &quot;Mosquito Range&quot; &quot;San
Juan Mountains&quot; &quot;Sangre de Cristo Range&quot; ...
## .. ..$ : chr [1:5] &quot;Elk Mountains&quot; &quot;Front Range&quot;
&quot;Mosquito Range&quot; &quot;San Juan Mountains&quot; ...
## $ p.adjust.method: chr &quot;bonferroni&quot;
## - attr(*, &quot;class&quot;)= chr &quot;pairwise.htest&quot;</code></pre>
<pre class="r"><code>glimpse(pairwise.t.test(x14$Isolation_mi, x14$Mt_Range, p.adj=&quot;bonferroni&quot;))</code></pre>
<pre><code>## List of 4
## $ method : chr &quot;t tests with pooled SD&quot;
## $ data.name : chr &quot;x14$Isolation_mi and x14$Mt_Range&quot;
## $ p.value : num [1:5, 1:5] 1 1 1 1 1 NA 1 1 1 1 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:5] &quot;Front Range&quot; &quot;Mosquito Range&quot; &quot;San
Juan Mountains&quot; &quot;Sangre de Cristo Range&quot; ...
## .. ..$ : chr [1:5] &quot;Elk Mountains&quot; &quot;Front Range&quot;
&quot;Mosquito Range&quot; &quot;San Juan Mountains&quot; ...
## $ p.adjust.method: chr &quot;bonferroni&quot;
## - attr(*, &quot;class&quot;)= chr &quot;pairwise.htest&quot;</code></pre>
<pre class="r"><code>glimpse(pairwise.t.test(x14$Distance_mi, x14$Mt_Range, p.adj=&quot;bonferroni&quot;))</code></pre>
<pre><code>## List of 4
## $ method : chr &quot;t tests with pooled SD&quot;
## $ data.name : chr &quot;x14$Distance_mi and x14$Mt_Range&quot;
## $ p.value : num [1:5, 1:5] 1 0.00818 1 1 1 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:5] &quot;Front Range&quot; &quot;Mosquito Range&quot; &quot;San
Juan Mountains&quot; &quot;Sangre de Cristo Range&quot; ...
## .. ..$ : chr [1:5] &quot;Elk Mountains&quot; &quot;Front Range&quot;
&quot;Mosquito Range&quot; &quot;San Juan Mountains&quot; ...
## $ p.adjust.method: chr &quot;bonferroni&quot;
## - attr(*, &quot;class&quot;)= chr &quot;pairwise.htest&quot;</code></pre>
<pre class="r"><code>glimpse(pairwise.t.test(x14$Ele_Gain_ft, x14$Mt_Range, p.adj=&quot;bonferroni&quot;))</code></pre>
<pre><code>## List of 4
## $ method : chr &quot;t tests with pooled SD&quot;
## $ data.name : chr &quot;x14$Ele_Gain_ft and x14$Mt_Range&quot;
## $ p.value : num [1:5, 1:5] 1 0.00528 1 1 1 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:5] &quot;Front Range&quot; &quot;Mosquito Range&quot; &quot;San
Juan Mountains&quot; &quot;Sangre de Cristo Range&quot; ...
## .. ..$ : chr [1:5] &quot;Elk Mountains&quot; &quot;Front Range&quot;
&quot;Mosquito Range&quot; &quot;San Juan Mountains&quot; ...
## $ p.adjust.method: chr &quot;bonferroni&quot;
## - attr(*, &quot;class&quot;)= chr &quot;pairwise.htest&quot;</code></pre>
<pre class="r"><code>glimpse(pairwise.t.test(x14$Low, x14$Mt_Range, p.adj=&quot;bonferroni&quot;))</code></pre>
<pre><code>## List of 4
## $ method : chr &quot;t tests with pooled SD&quot;
## $ data.name : chr &quot;x14$Low and x14$Mt_Range&quot;
## $ p.value : num [1:5, 1:5] 1.22e-13 1.12e-09 1.00 1.00
8.01e-02 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:5] &quot;Front Range&quot; &quot;Mosquito Range&quot; &quot;San
Juan Mountains&quot; &quot;Sangre de Cristo Range&quot; ...
## .. ..$ : chr [1:5] &quot;Elk Mountains&quot; &quot;Front Range&quot;
&quot;Mosquito Range&quot; &quot;San Juan Mountains&quot; ...
## $ p.adjust.method: chr &quot;bonferroni&quot;
## - attr(*, &quot;class&quot;)= chr &quot;pairwise.htest&quot;</code></pre>
<pre class="r"><code>glimpse(pairwise.t.test(x14$High, x14$Mt_Range, p.adj=&quot;bonferroni&quot;))</code></pre>
<pre><code>## List of 4
## $ method : chr &quot;t tests with pooled SD&quot;
## $ data.name : chr &quot;x14$High and x14$Mt_Range&quot;
## $ p.value : num [1:5, 1:5] 1.23e-14 4.82e-11 1.00 1.00
9.16e-02 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:5] &quot;Front Range&quot; &quot;Mosquito Range&quot; &quot;San
Juan Mountains&quot; &quot;Sangre de Cristo Range&quot; ...
## .. ..$ : chr [1:5] &quot;Elk Mountains&quot; &quot;Front Range&quot;
&quot;Mosquito Range&quot; &quot;San Juan Mountains&quot; ...
## $ p.adjust.method: chr &quot;bonferroni&quot;
## - attr(*, &quot;class&quot;)= chr &quot;pairwise.htest&quot;</code></pre>
<p><em>A one-way MANOVA was conducted to determine the effect of Mountain Rane on 7 numeric variables (Elevation_ft, Prominence_ft, Isolation_mi, Distance_mi, Ele_Gain_ft, Low, and High). Significant differences were found in the numeric variables which differed across mountain ranges. An univariate ANOVA was used for each dependent variable, as a follow up test for the MANOVA, and proved that four of the seven variables, Distance_mi, Ele_Gain_ft, Low and High, are all dependent on the Mountain Range. Post hoc analysis was performed to conduct pairwise t-tests on each dependent variable and found a significant difference in some Mountain Ranges when testing the Ele_Gain_ft, Low, and High variables using the bonferroni correction. If the Bonferroni correction is not used, the probability of making a type-1 error increase with each test conducted, to fix this, the Bonferroni correction divides .05 by the number of tests conducted, in order to take into account the multiple tests and decrease the possibility for error. It is unlikely that the data met all the assumptions for a MANOVA test, multivariate normality is highly variable across the dependent variables, but according to covariance matrices there is a somewhat equal variance occuring in the set. </em></p>
</div>
<div id="question2" class="section level1">
<h1>Question2</h1>
<pre class="r"><code>library(vegan)
x141&lt;-x14%&gt;%select(-Mt_Peak, -St_Route, -Difficulty, -Lat, -Long, -fourteener, -Difficulty)
dist&lt;-vegdist(sqrt(x141[,-c(2)]),method=&quot;bray&quot;)
distS&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Sawatch Range&quot;,-c(2)]),method=&quot;bray&quot;)
distSC&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Sangre de Cristo Range&quot;,-c(2)]),method=&quot;bray&quot;)
distSJ&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;San Juan Range&quot;,-c(2)]),method=&quot;bray&quot;)
distM&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Mosquito Range&quot;,-c(2)]),method=&quot;bray&quot;)
distE&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Elk Range&quot;,-c(2)]),method=&quot;bray&quot;)
distF&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Front Range&quot;,-c(2)]),method=&quot;bray&quot;)
SSR&lt;-sum(distS^2)/15+sum(distSC^2)/10+sum(distSJ^2)/14+
  sum(distM^2)/6+sum(distE^2)/7+sum(distF^2)/6
SST&lt;-sum(dist^2)/58
Fstat&lt;-(SST-SSR)/(SSR/52)
Fstat</code></pre>
<pre><code>## [1] 285.2624</code></pre>
<pre class="r"><code>perm.sampdist&lt;-replicate(5000,{
   new&lt;-x141
   new$Mt_Range&lt;-sample(x141$Mt_Range)
   dist&lt;-vegdist(sqrt(x141[,-c(2)]),method=&quot;bray&quot;)
distS&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Sawatch Range&quot;,-c(2)]),method=&quot;bray&quot;)
distSC&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Sangre de Cristo Range&quot;,-c(2)]),method=&quot;bray&quot;)
distSJ&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;San Juan Range&quot;,-c(2)]),method=&quot;bray&quot;)
distM&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Mosquito Range&quot;,-c(2)]),method=&quot;bray&quot;)
distE&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Elk Range&quot;,-c(2)]),method=&quot;bray&quot;)
distF&lt;-vegdist(sqrt(x141[x141$Mt_Range==&quot;Front Range&quot;,-c(2)]),method=&quot;bray&quot;)
  SSR&lt;-sum(distS^2)/15+sum(distSC^2)/10+sum(distSJ^2)/14+
    sum(distM^2)/6+sum(distE^2)/7+sum(distF^2)/6
SST&lt;-sum(dist^2)/58
(SST-SSR)/(SSR/52)
 })
 mean(perm.sampdist&gt;Fstat)</code></pre>
<pre><code>## [1] 0</code></pre>
<pre class="r"><code>glimpse(adonis(dist~Mt_Range,data=x141, method=&quot;bray&quot;))</code></pre>
<pre><code>## List of 7
## $ aov.tab :Classes &#39;anova&#39; and &#39;data.frame&#39;: 3 obs. of 6
variables:
## ..$ Df : num [1:3] 5 52 57
## ..$ SumsOfSqs: num [1:3] 0.683 0.192 0.875
## ..$ MeanSqs : num [1:3] 0.1366 0.00369 NA
## ..$ F.Model : num [1:3] 37 NA NA
## ..$ R2 : num [1:3] 0.781 0.219 1
## ..$ Pr(&gt;F) : num [1:3] 0.001 NA NA
## ..- attr(*, &quot;heading&quot;)= chr [1:2] &quot;Permutation:
free\nNumber of permutations: 999\n&quot; &quot;Terms added
sequentially (first to last)\n&quot;
## $ call : language adonis(formula = dist ~ Mt_Range, data
= x141, method = &quot;bray&quot;)
## $ coefficients: NULL
## $ coef.sites : num [1:6, 1:58] 0.2343 0.0937 -0.1204
-0.1083 0.0508 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:6] &quot;(Intercept)&quot; &quot;Mt_Range1&quot; &quot;Mt_Range2&quot;
&quot;Mt_Range3&quot; ...
## .. ..$ : NULL
## $ f.perms : num [1:999, 1] 1.862 0.817 0.288 1.184 0.658
...
## $ model.matrix: num [1:58, 1:6] 1 1 1 1 1 1 1 1 1 1 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:58] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
## .. ..$ : chr [1:6] &quot;(Intercept)&quot; &quot;Mt_Range1&quot; &quot;Mt_Range2&quot;
&quot;Mt_Range3&quot; ...
## $ terms :Classes &#39;terms&#39;, &#39;formula&#39; language dist ~
Mt_Range
## .. ..- attr(*, &quot;variables&quot;)= language list(dist,
Mt_Range)
## .. ..- attr(*, &quot;factors&quot;)= int [1:2, 1] 0 1
## .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..- attr(*, &quot;term.labels&quot;)= chr &quot;Mt_Range&quot;
## .. ..- attr(*, &quot;order&quot;)= int 1
## .. ..- attr(*, &quot;intercept&quot;)= int 1
## .. ..- attr(*, &quot;response&quot;)= int 1
## .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment:
R_GlobalEnv&gt;
## - attr(*, &quot;class&quot;)= chr &quot;adonis&quot;</code></pre>
<pre class="r"><code> SST&lt;- sum(dist^2)/58
SSW&lt;-x141%&gt;%group_by(Mt_Range)%&gt;%select(Elevation_ft, Prominence_ft, Isolation_mi, Distance_mi, Ele_Gain_ft, Low, High)%&gt;%
  do(d=dist(.[2:2],&quot;euclidean&quot;))%&gt;%ungroup()%&gt;%
  summarize(sum(d[[1]]^2)/15 + sum(d[[2]]^2)/10+ sum(d[[3]]^2)/14+ sum(d[[4]]^2)/6+ sum(d[[5]]^2)/7+ sum(d[[6]]^2)/6)%&gt;%pull
F_obs&lt;-((SST-SSW)/2)/(SSW/147)
 library(dplyr)
 Fs&lt;-replicate(1000,{
   new&lt;-x141%&gt;%mutate(Mt_Range=sample(Mt_Range))
   SSW&lt;-new%&gt;%group_by(Mt_Range)%&gt;%select(Elevation_ft, Prominence_ft, Isolation_mi, Distance_mi, Ele_Gain_ft, Low, High)%&gt;% do(d=dist(.[2:2],&quot;euclidean&quot;))%&gt;%ungroup()%&gt;%
     summarize(sum(d[[1]]^2)/15 + sum(d[[2]]^2)/10 +sum(d[[3]]^2)/14 +sum(d[[4]]^2)/6 +
                 sum(d[[5]]^2)/7 +sum(d[[6]]^2)/6)
   ((SST-SSW)/2)/(SSW/52)
 })
 Fs&lt;-as.numeric(Fs)
 { hist(Fs, prob=T); abline(v=F_obs, col=&quot;red&quot;)}</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code> mean(Fs&gt;F_obs)</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code> t&lt;-vector()
 for(i in 1:10000){
   samp&lt;- rnorm(58, mean=7.6)
   t[i]&lt;-(mean(samp)-7.6)/(sd(samp)/sqrt(58))
 }
data.frame(t)%&gt;%ggplot(aes(t))+geom_histogram(aes(y=..density..), bins=30)+
  stat_function(fun=dt,args=list(df=57),geom=&quot;line&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-2-2.png" width="768" style="display: block; margin: auto;" /></p>
<p><em>The Null Hypothesis for the Colorado Fourteener data is that there is no statistically relevant difference in the 6 Mountain Ranges when comparing the 7 numerical variables. The Alternative Hypothesis for the Colorado Fourteener data is that there is a statistically relevant difference between the 6 Mountain Ranges when looking at the 7 numerical variables listed in the dataset. The results of the Randomization PERMANOVA test suggest that the Mountain Ranges vary in terms of the 7 numerical variables, thus we can reject the Null Hypothesis and accept the Alternative Hypothesis, although the test suggests that it is less significant than the MANOVA determined.</em></p>
</div>
<div id="question-3" class="section level1">
<h1>Question 3</h1>
<pre class="r"><code>x14%&gt;%summarize(mean(Distance_mi, na.rm=T))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   `mean(Distance_mi, na.rm = T)`
##                            &lt;dbl&gt;
## 1                           11.2</code></pre>
<pre class="r"><code>glimpse(data.frame(&quot;Distance_c&quot;= x14$Distance_mi - mean(x14$Distance_mi, na.rm=T)))</code></pre>
<pre><code>## Observations: 58
## Variables: 1
## $ Distance_c &lt;dbl&gt; -1.6767241, 3.3232759, 2.8232759,
5.8232759, -1.9267241, -3.6767241, 2.8232759…</code></pre>
<pre class="r"><code>x14$Distance_c &lt;- x14$Distance_mi - mean(x14$Distance_mi, na.rm=T)
fit&lt;-lm(Ele_Gain_ft ~ Mt_Range*Distance_c, data=x14)
glimpse(summary(fit))</code></pre>
<pre><code>## List of 11
## $ call : language lm(formula = Ele_Gain_ft ~ Mt_Range *
Distance_c, data = x14)
## $ terms :Classes &#39;terms&#39;, &#39;formula&#39; language Ele_Gain_ft
~ Mt_Range * Distance_c
## .. ..- attr(*, &quot;variables&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;factors&quot;)= int [1:3, 1:3] 0 1 0 0 0 1 0
1 1
## .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..- attr(*, &quot;term.labels&quot;)= chr [1:3] &quot;Mt_Range&quot;
&quot;Distance_c&quot; &quot;Mt_Range:Distance_c&quot;
## .. ..- attr(*, &quot;order&quot;)= int [1:3] 1 1 2
## .. ..- attr(*, &quot;intercept&quot;)= int 1
## .. ..- attr(*, &quot;response&quot;)= int 1
## .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment:
R_GlobalEnv&gt;
## .. ..- attr(*, &quot;predvars&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:3] &quot;numeric&quot;
&quot;character&quot; &quot;numeric&quot;
## .. .. ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;Ele_Gain_ft&quot;
&quot;Mt_Range&quot; &quot;Distance_c&quot;
## $ residuals : Named num [1:58] 236.8 -702.2 -528.3
-120.3 73.7 ...
## ..- attr(*, &quot;names&quot;)= chr [1:58] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
## $ coefficients : num [1:12, 1:4] 4662.6 -816.3 -314.9
-416.3 -14.2 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:4] &quot;Estimate&quot; &quot;Std. Error&quot; &quot;t value&quot;
&quot;Pr(&gt;|t|)&quot;
## $ aliased : Named logi [1:12] FALSE FALSE FALSE FALSE
FALSE FALSE ...
## ..- attr(*, &quot;names&quot;)= chr [1:12] &quot;(Intercept)&quot;
&quot;Mt_RangeFront Range&quot; &quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan
Juan Mountains&quot; ...
## $ sigma : num 482
## $ df : int [1:3] 12 46 12
## $ r.squared : num 0.893
## $ adj.r.squared: num 0.867
## $ fstatistic : Named num [1:3] 34.9 11 46
## ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;value&quot; &quot;numdf&quot; &quot;dendf&quot;
## $ cov.unscaled : num [1:12, 1:12] 0.191 -0.191 -0.191
-0.191 -0.191 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## - attr(*, &quot;class&quot;)= chr &quot;summary.lm&quot;</code></pre>
<pre class="r"><code>ggplot(x14, aes(x=Ele_Gain_ft, y=Distance_mi,color=Mt_Range))+geom_point()+stat_smooth(method=&quot;lm&quot;,se=FALSE,fullrange=TRUE)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot(fit, aes(Ele_Gain_ft,Distance_c))+geom_point()+geom_smooth(method = &#39;lm&#39;, se=F)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids&lt;-fit$residuals
fitvals&lt;-fit$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0,color=&#39;red&#39;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids),bins=25)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-4.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_qq(aes(sample=resids))</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-3-5.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(lmtest)
library(sandwich)
coeftest(fit, vcov = vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 4662.631 75.105 62.0812 &lt; 2.2e-16 ***
## Mt_RangeFront Range -816.342 237.727 -3.4339 0.00127 **
## Mt_RangeMosquito Range -314.871 1665.684 -0.1890 0.85090
## Mt_RangeSan Juan Mountains -416.270 166.136 -2.5056
0.01583 *
## Mt_RangeSangre de Cristo Range -14.165 153.637 -0.0922
0.92694
## Mt_RangeSawatch Range 48.396 191.633 0.2525 0.80174
## Distance_c 96.357 18.684 5.1572 5.177e-06 ***
## Mt_RangeFront Range:Distance_c 162.222 64.936 2.4982
0.01612 *
## Mt_RangeMosquito Range:Distance_c 208.188 255.556 0.8146
0.41947
## Mt_RangeSan Juan Mountains:Distance_c 171.117 28.601
5.9829 3.072e-07 ***
## Mt_RangeSangre de Cristo Range:Distance_c 242.249 37.070
6.5350 4.552e-08 ***
## Mt_RangeSawatch Range:Distance_c 51.426 68.742 0.7481
0.45820
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>glimpse(fit%&gt;%summary(robust=T))</code></pre>
<pre><code>## List of 11
## $ call : language lm(formula = Ele_Gain_ft ~ Mt_Range *
Distance_c, data = x14)
## $ terms :Classes &#39;terms&#39;, &#39;formula&#39; language Ele_Gain_ft
~ Mt_Range * Distance_c
## .. ..- attr(*, &quot;variables&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;factors&quot;)= int [1:3, 1:3] 0 1 0 0 0 1 0
1 1
## .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..- attr(*, &quot;term.labels&quot;)= chr [1:3] &quot;Mt_Range&quot;
&quot;Distance_c&quot; &quot;Mt_Range:Distance_c&quot;
## .. ..- attr(*, &quot;order&quot;)= int [1:3] 1 1 2
## .. ..- attr(*, &quot;intercept&quot;)= int 1
## .. ..- attr(*, &quot;response&quot;)= int 1
## .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment:
R_GlobalEnv&gt;
## .. ..- attr(*, &quot;predvars&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:3] &quot;numeric&quot;
&quot;character&quot; &quot;numeric&quot;
## .. .. ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;Ele_Gain_ft&quot;
&quot;Mt_Range&quot; &quot;Distance_c&quot;
## $ residuals : Named num [1:58] 236.8 -702.2 -528.3
-120.3 73.7 ...
## ..- attr(*, &quot;names&quot;)= chr [1:58] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
## $ coefficients : num [1:12, 1:4] 4662.6 -816.3 -314.9
-416.3 -14.2 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:4] &quot;Estimate&quot; &quot;Std. Error&quot; &quot;t value&quot;
&quot;Pr(&gt;|t|)&quot;
## $ aliased : Named logi [1:12] FALSE FALSE FALSE FALSE
FALSE FALSE ...
## ..- attr(*, &quot;names&quot;)= chr [1:12] &quot;(Intercept)&quot;
&quot;Mt_RangeFront Range&quot; &quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan
Juan Mountains&quot; ...
## $ sigma : num 482
## $ df : int [1:3] 12 46 12
## $ r.squared : num 0.893
## $ adj.r.squared: num 0.867
## $ fstatistic : Named num [1:3] 34.9 11 46
## ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;value&quot; &quot;numdf&quot; &quot;dendf&quot;
## $ cov.unscaled : num [1:12, 1:12] 0.191 -0.191 -0.191
-0.191 -0.191 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## - attr(*, &quot;class&quot;)= chr &quot;summary.lm&quot;</code></pre>
<pre class="r"><code>glimpse(summary(fit))</code></pre>
<pre><code>## List of 11
## $ call : language lm(formula = Ele_Gain_ft ~ Mt_Range *
Distance_c, data = x14)
## $ terms :Classes &#39;terms&#39;, &#39;formula&#39; language Ele_Gain_ft
~ Mt_Range * Distance_c
## .. ..- attr(*, &quot;variables&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;factors&quot;)= int [1:3, 1:3] 0 1 0 0 0 1 0
1 1
## .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..- attr(*, &quot;term.labels&quot;)= chr [1:3] &quot;Mt_Range&quot;
&quot;Distance_c&quot; &quot;Mt_Range:Distance_c&quot;
## .. ..- attr(*, &quot;order&quot;)= int [1:3] 1 1 2
## .. ..- attr(*, &quot;intercept&quot;)= int 1
## .. ..- attr(*, &quot;response&quot;)= int 1
## .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment:
R_GlobalEnv&gt;
## .. ..- attr(*, &quot;predvars&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:3] &quot;numeric&quot;
&quot;character&quot; &quot;numeric&quot;
## .. .. ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;Ele_Gain_ft&quot;
&quot;Mt_Range&quot; &quot;Distance_c&quot;
## $ residuals : Named num [1:58] 236.8 -702.2 -528.3
-120.3 73.7 ...
## ..- attr(*, &quot;names&quot;)= chr [1:58] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
## $ coefficients : num [1:12, 1:4] 4662.6 -816.3 -314.9
-416.3 -14.2 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:4] &quot;Estimate&quot; &quot;Std. Error&quot; &quot;t value&quot;
&quot;Pr(&gt;|t|)&quot;
## $ aliased : Named logi [1:12] FALSE FALSE FALSE FALSE
FALSE FALSE ...
## ..- attr(*, &quot;names&quot;)= chr [1:12] &quot;(Intercept)&quot;
&quot;Mt_RangeFront Range&quot; &quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan
Juan Mountains&quot; ...
## $ sigma : num 482
## $ df : int [1:3] 12 46 12
## $ r.squared : num 0.893
## $ adj.r.squared: num 0.867
## $ fstatistic : Named num [1:3] 34.9 11 46
## ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;value&quot; &quot;numdf&quot; &quot;dendf&quot;
## $ cov.unscaled : num [1:12, 1:12] 0.191 -0.191 -0.191
-0.191 -0.191 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## - attr(*, &quot;class&quot;)= chr &quot;summary.lm&quot;</code></pre>
<pre class="r"><code>fit1&lt;-lm(Ele_Gain_ft ~ Mt_Range+Distance_c, data=x14)
glimpse(summary(fit1))</code></pre>
<pre><code>## List of 11
## $ call : language lm(formula = Ele_Gain_ft ~ Mt_Range +
Distance_c, data = x14)
## $ terms :Classes &#39;terms&#39;, &#39;formula&#39; language Ele_Gain_ft
~ Mt_Range + Distance_c
## .. ..- attr(*, &quot;variables&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;factors&quot;)= int [1:3, 1:2] 0 1 0 0 0 1
## .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..- attr(*, &quot;term.labels&quot;)= chr [1:2] &quot;Mt_Range&quot;
&quot;Distance_c&quot;
## .. ..- attr(*, &quot;order&quot;)= int [1:2] 1 1
## .. ..- attr(*, &quot;intercept&quot;)= int 1
## .. ..- attr(*, &quot;response&quot;)= int 1
## .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment:
R_GlobalEnv&gt;
## .. ..- attr(*, &quot;predvars&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:3] &quot;numeric&quot;
&quot;character&quot; &quot;numeric&quot;
## .. .. ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;Ele_Gain_ft&quot;
&quot;Mt_Range&quot; &quot;Distance_c&quot;
## $ residuals : Named num [1:58] 333 -1049 -831 337 192
...
## ..- attr(*, &quot;names&quot;)= chr [1:58] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
## $ coefficients : num [1:7, 1:4] 4307.4 -455.8 -381 -31.5
478.9 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:7] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:4] &quot;Estimate&quot; &quot;Std. Error&quot; &quot;t value&quot;
&quot;Pr(&gt;|t|)&quot;
## $ aliased : Named logi [1:7] FALSE FALSE FALSE FALSE
FALSE FALSE ...
## ..- attr(*, &quot;names&quot;)= chr [1:7] &quot;(Intercept)&quot;
&quot;Mt_RangeFront Range&quot; &quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan
Juan Mountains&quot; ...
## $ sigma : num 559
## $ df : int [1:3] 7 51 7
## $ r.squared : num 0.841
## $ adj.r.squared: num 0.822
## $ fstatistic : Named num [1:3] 44.8 6 51
## ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;value&quot; &quot;numdf&quot; &quot;dendf&quot;
## $ cov.unscaled : num [1:7, 1:7] 0.15 -0.149 -0.166
-0.147 -0.146 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:7] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:7] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## - attr(*, &quot;class&quot;)= chr &quot;summary.lm&quot;</code></pre>
<pre class="r"><code>lrtest(fit1,fit)</code></pre>
<pre><code>## Likelihood ratio test
##
## Model 1: Ele_Gain_ft ~ Mt_Range + Distance_c
## Model 2: Ele_Gain_ft ~ Mt_Range * Distance_c
## #Df LogLik Df Chisq Pr(&gt;Chisq)
## 1 8 -445.48
## 2 13 -433.94 5 23.075 0.0003266 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>lrtest(fit1)</code></pre>
<pre><code>## Likelihood ratio test
##
## Model 1: Ele_Gain_ft ~ Mt_Range + Distance_c
## Model 2: Ele_Gain_ft ~ 1
## #Df LogLik Df Chisq Pr(&gt;Chisq)
## 1 8 -445.48
## 2 2 -498.72 -6 106.48 &lt; 2.2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p><em>The Intercept determines the predicted average Elevation Gain (ft) of the standard route for the Elk Mountain range, which was 4662.63ft. The 5 other Mountain Ranges all had lower predicted average Elevation Gains (ft) than the Elk Mountain Range, except for the Sawatch Range, which had an Elevation Gain (ft) 48.4 feet steeper than the Elk Mountains. If a route has an average centered trail Distance (miles), then the predicted Elevation Gain (ft) would be 96.36 ft steeper than the average Elk Mountain trail. When the centered trail Distance (miles) interacted with each Mountain Range, all predicted Elevation Gain (ft) was higher than the intercept, with the interaction for the Sangre de Cristo Range being the steepest, at 242.25 feet steeper than the Intercept. Robust standard errors are used to lessen the effect of bias when data is heteroskedastic, the robust standard errors produced returns with more significant data than the original linear regression model. The Intercept, Front Range, and the interaction between Sangre de Cristo Mountains and the centered distance remained the same level of significance. The centered distance, and the interaction between the San Juan Mountains and the centered distance increased in significance, and the San Juan Mountains without interactions became significant when it previously was not. The interaction between the Front Range and centered Distance decreased in significance with robust standard errors, suggesting that a bias was previously effecting the results of the linear model. Approximately .8929, or 89.29% of the outcome variation can be explained by the model. The model with no interactions was proven to be significantly different than both the model with interactions and the null model using the likelihood ratio test</em></p>
</div>
<div id="question-4" class="section level1">
<h1>Question 4</h1>
<pre class="r"><code>glimpse(summary(fit))</code></pre>
<pre><code>## List of 11
## $ call : language lm(formula = Ele_Gain_ft ~ Mt_Range *
Distance_c, data = x14)
## $ terms :Classes &#39;terms&#39;, &#39;formula&#39; language Ele_Gain_ft
~ Mt_Range * Distance_c
## .. ..- attr(*, &quot;variables&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;factors&quot;)= int [1:3, 1:3] 0 1 0 0 0 1 0
1 1
## .. .. ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..- attr(*, &quot;term.labels&quot;)= chr [1:3] &quot;Mt_Range&quot;
&quot;Distance_c&quot; &quot;Mt_Range:Distance_c&quot;
## .. ..- attr(*, &quot;order&quot;)= int [1:3] 1 1 2
## .. ..- attr(*, &quot;intercept&quot;)= int 1
## .. ..- attr(*, &quot;response&quot;)= int 1
## .. ..- attr(*, &quot;.Environment&quot;)=&lt;environment:
R_GlobalEnv&gt;
## .. ..- attr(*, &quot;predvars&quot;)= language list(Ele_Gain_ft,
Mt_Range, Distance_c)
## .. ..- attr(*, &quot;dataClasses&quot;)= Named chr [1:3] &quot;numeric&quot;
&quot;character&quot; &quot;numeric&quot;
## .. .. ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;Ele_Gain_ft&quot;
&quot;Mt_Range&quot; &quot;Distance_c&quot;
## $ residuals : Named num [1:58] 236.8 -702.2 -528.3
-120.3 73.7 ...
## ..- attr(*, &quot;names&quot;)= chr [1:58] &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
## $ coefficients : num [1:12, 1:4] 4662.6 -816.3 -314.9
-416.3 -14.2 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:4] &quot;Estimate&quot; &quot;Std. Error&quot; &quot;t value&quot;
&quot;Pr(&gt;|t|)&quot;
## $ aliased : Named logi [1:12] FALSE FALSE FALSE FALSE
FALSE FALSE ...
## ..- attr(*, &quot;names&quot;)= chr [1:12] &quot;(Intercept)&quot;
&quot;Mt_RangeFront Range&quot; &quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan
Juan Mountains&quot; ...
## $ sigma : num 482
## $ df : int [1:3] 12 46 12
## $ r.squared : num 0.893
## $ adj.r.squared: num 0.867
## $ fstatistic : Named num [1:3] 34.9 11 46
## ..- attr(*, &quot;names&quot;)= chr [1:3] &quot;value&quot; &quot;numdf&quot; &quot;dendf&quot;
## $ cov.unscaled : num [1:12, 1:12] 0.191 -0.191 -0.191
-0.191 -0.191 ...
## ..- attr(*, &quot;dimnames&quot;)=List of 2
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## .. ..$ : chr [1:12] &quot;(Intercept)&quot; &quot;Mt_RangeFront Range&quot;
&quot;Mt_RangeMosquito Range&quot; &quot;Mt_RangeSan Juan Mountains&quot; ...
## - attr(*, &quot;class&quot;)= chr &quot;summary.lm&quot;</code></pre>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))[,1:2]</code></pre>
<pre><code>## Estimate Std. Error
## (Intercept) 4662.63070 75.10537
## Mt_RangeFront Range -816.34156 237.72743
## Mt_RangeMosquito Range -314.87077 1665.68428
## Mt_RangeSan Juan Mountains -416.27008 166.13615
## Mt_RangeSangre de Cristo Range -14.16498 153.63704
## Mt_RangeSawatch Range 48.39597 191.63270
## Distance_c 96.35713 18.68394
## Mt_RangeFront Range:Distance_c 162.22227 64.93561
## Mt_RangeMosquito Range:Distance_c 208.18832 255.55567
## Mt_RangeSan Juan Mountains:Distance_c 171.11712 28.60100
## Mt_RangeSangre de Cristo Range:Distance_c 242.24886
37.06968
## Mt_RangeSawatch Range:Distance_c 51.42631 68.74193</code></pre>
<pre class="r"><code>library(sandwich)
library(lmtest)
set.seed(348)
boot_dat&lt;-x14[sample(nrow(x14),replace=TRUE),]
samp_distv&lt;-replicate(1000, {
  boot_dat&lt;- x14[sample(nrow(x14), replace=TRUE),]
  fit2&lt;-lm(Ele_Gain_ft ~ Mt_Range*Distance_c, data=boot_dat)
  coeftest(fit2)
})
do.call(rbind,lapply(samp_distv,unlist))%&gt;%as.data.frame%&gt;%summarize_all(sd,na.rm=T)</code></pre>
<pre><code>##   Estimate Std. Error  t value  Pr(&gt;|t|)
## 1 1402.186   443.0335 6.915959 0.3165721</code></pre>
<p><em>The bootstrapped model, in general has lower standard error measurements than the original glm, the standard errors for the Intercept, Front Range, San Juan, Sangre de Cristo, Sawatch, centered distance, the interaction between the Front Range and centered distance, and the interaction between the San Juan Range and centered distance. This decrease in standard error suggests a lower possibility of error when determining whether these variables have an effect on the Elevation Gain (feet) of the Standard Trail. The bootstrapped model also increased the significance of the Front Range, San Juan Range, the centered Distance (miles), the interaction between the Front Range and the centered distance, the interaction between the Mosquito Range and the centered distance, and the interaction between the San Juan Range and the centered distance, when compared to the original glm and the glm with robust standard errors. This may mean that these variables are a more significant predictor of the Elevation Gain (feet) than previously expected.</em></p>
</div>
<div id="question-5" class="section level1">
<h1>Question 5</h1>
<pre class="r"><code>library(tidyr)
odds&lt;-function(p)p/(1-p)
p&lt;-seq(0,1,by=.1)
cbind(p, odds=odds(p))%&gt;%round(4)</code></pre>
<pre><code>##         p   odds
##  [1,] 0.0 0.0000
##  [2,] 0.1 0.1111
##  [3,] 0.2 0.2500
##  [4,] 0.3 0.4286
##  [5,] 0.4 0.6667
##  [6,] 0.5 1.0000
##  [7,] 0.6 1.5000
##  [8,] 0.7 2.3333
##  [9,] 0.8 4.0000
## [10,] 0.9 9.0000
## [11,] 1.0    Inf</code></pre>
<pre class="r"><code>logit&lt;-function(p)log(odds(p))
fit14&lt;-glm(fourteener~Distance_mi+High,data=x14,family=binomial(link=&quot;logit&quot;))
coef(fit14)</code></pre>
<pre><code>##   (Intercept)   Distance_mi          High 
##  2.363052e+00 -2.505357e-02  3.646864e-05</code></pre>
<pre class="r"><code>exp(coef(fit14))</code></pre>
<pre><code>## (Intercept) Distance_mi        High 
##  10.6233237   0.9752577   1.0000365</code></pre>
<pre class="r"><code>logistic&lt;-function(x){exp(x)/(1+exp(x))}
pca1&lt;-princomp(x14[c(&#39;fourteener&#39;, &#39;Distance_mi&#39;, &#39;High&#39;)])
x14$predictor&lt;-pca1$scores[,1]
fit15&lt;-glm(fourteener~predictor,data=x14,family=&quot;binomial&quot;)
x14$prob&lt;- predict(fit15, type=&quot;response&quot;)
 table(predict=as.numeric(x14$prob&gt;.9),truth=x14$fourteener)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict  0  1 Sum
##     0    3 17  20
##     1    2 36  38
##     Sum  5 53  58</code></pre>
<pre class="r"><code> TPR&lt;-36/53
 TNR&lt;-3/5
 PPV&lt;-36/38
 ACC&lt;-(3+36)/58
x14$logit.&lt;-predict(fit14)
x14$fourteener.&lt;-factor(x14$fourteener,levels=c(1,0))
ggplot(x14,aes(logit., fill=fourteener.))+geom_density(alpha=.3)+geom_vline(xintercept=0,lty=2)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>sens&lt;-function(p,data=x14,y=fourteener.) mean(x14[x14$fourteener.==1,]$prob&gt;p)
spec&lt;-function(p,data=x14,y=fourteener.) mean(x14[x14$fourteener.==0,]$prob&lt;p)
sensitivity5&lt;-sapply(seq(0,1,.01),sens,x14)
specificity5&lt;-sapply(seq(0,1,.01),spec,x14)
ROC&lt;-data.frame(sensitivity5,specificity5,cutoff=seq(0,1,.01))
ROC%&gt;%gather(key,rate,-cutoff)%&gt;%ggplot(aes(cutoff,rate,color=key))+geom_path()+geom_vline(xintercept=c(.1,.5,.9),lty=2,color=&quot;gray50&quot;)</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-5-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ROC$TPR5&lt;-rev(sensitivity5)
ROC$FPR5&lt;-rev(1-specificity5)
ROC%&gt;%ggplot(aes(FPR5,TPR5))+geom_path(size=1.5)+geom_segment(aes(x=0,y=0,xend=1,yend=1),lty=2)+scale_x_continuous(limits=c(0,1))</code></pre>
<p><img src="/Project2_files/figure-html/unnamed-chunk-5-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code> widths5&lt;-diff(ROC$FPR5)
heights5&lt;-vector()
for(i in 1:100) heights5[i]&lt;-ROC$TPR5[i]+ROC$TPR5[i+1] 
AUC5&lt;-sum(heights5*widths5/2)
AUC5%&gt;%round(3)</code></pre>
<pre><code>## [1] 0.649</code></pre>
<pre class="r"><code>x15&lt;-x14%&gt;%select( -predictor, -prob, -logit., -fourteener.)
x15&lt;- X14er %&gt;% transmute(ID = ID, Mt_Peak = `Mountain Peak`, Mt_Range=`Mountain Range`, St_Route=`Standard Route`,Difficulty=Difficulty,Lat=Lat, Long=Long, Elevation_ft=Elevation_ft,  Prominence_ft=Prominence_ft, Isolation_mi=Isolation_mi,  Distance_mi=Distance_mi, Ele_Gain_ft = `Elevation Gain_ft`, Low= `Traffic Low`, High=`Traffic High`, fourteener=as.numeric(fourteener==&quot;Y&quot;,1)) 
prob&lt;-predict(fit15,type=&quot;response&quot;)
class_diag&lt;-function(probs,truth){
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  TPR=cumsum(truth)/max(1,sum(truth))
  FPR=cumsum(!truth)/max(1,sum(!truth))
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  data.frame(acc,sens,spec,ppv,auc)
  }
class_diag(prob,x14$fourteener)</code></pre>
<pre><code>##         acc sens spec       ppv       auc
## 1 0.9137931    1    0 0.9137931 0.6641509</code></pre>
<pre class="r"><code>library(pROC)
x14&lt;-x14%&gt;%na.omit
set.seed(1234)
k=5
data1&lt;-x14[sample(nrow(x14)),]
folds&lt;-cut(seq(1:nrow(x14)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
  train&lt;-data1[folds!=i,]
  test&lt;-data1[folds==i,]
  truth=test$fourteener
  fit16&lt;-glm(fourteener~Distance_mi+High,data=train,family=&quot;binomial&quot;)
  probs&lt;-predict(fit16, newdata=test, type=&quot;response&quot;)
  diags&lt;-rbind(diags, class_diag(probs,truth))
}
apply(diags,2,mean)</code></pre>
<pre><code>##       acc      sens      spec       ppv       auc 
## 0.8969697 0.9818182 0.0000000 0.9121212 0.3981818</code></pre>
<p><em>The Intercept of the coefficient test corresponds with the log odds of the probability of being classified as a Fourteener, The Estimate for distance of the Standard trail (miles) suggests that for every 1 unit increase in the trail distance, the log odds of the probability of being a fourteener decreases by 2.5054e-02. For every 1 unit increase in the High Estimate of Visitors to the mountains, the log odds of probability of being classified as a fourteener increases by 3.6469e-05. The estimates are not statistically significant predictors of whether a mountain is classified as a fourteener or not. The accuracy of the model is moderate, with it correctly classifying whether a mountain is a fourteener or not 67% of the time. The TPR was .679, a moderately good score, predicting true positives correctly about 67.9% of the time. The model was worse at predicting True Negative values, correctly classifying them 60% of the time. The model had very good recall (PPV), with 94% of the mountains classified as fourteeners actually being fourteeners. The calculated AUC was .649, a poor value for predicting whether a mountain is classified as a fourteener or not, so trail distance in miles and the High estimate for visitors are not significant predictors of whether a mountain is a fourteener or not, and will not generate a model that can accurately predict this. When using the 5 fold cross validation method, our out of sample values for accuracy, and sensitvity are higher, suggesting this model was better at classifying whether a mountain is a fourteener, and has a better true positive rate, classifying more fourteeners correctly. The model did not return a true negative rate value, had a slightly lower ppv, and a lower auc, suggesting that the model is not as accurate as the previous method at correctly classifying the mountains in their correct categories.</em></p>
</div>
<div id="question-6" class="section level1">
<h1>Question 6</h1>
<pre class="r"><code>library(glmnet)
library(Matrix)
df = subset(x14, select = -c(Mt_Peak, St_Route,Difficulty,Mt_Range) )
df&lt;-as.vector(df)
fit17&lt;-lm(fourteener~.,data=df)
yhat&lt;-predict(fit17)
mean((df$fourteener-yhat)^2)</code></pre>
<pre><code>## [1] 6.579508e-31</code></pre>
<pre class="r"><code>set.seed(1234)
k=5
data1&lt;-df[sample(nrow(df)),]
folds&lt;-cut(seq(1:nrow(df)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
  train&lt;-data1[folds!=i,]
  test&lt;-data1[folds==i,]
  fit17&lt;-lm(fourteener~.,data=train)
  yhat&lt;-predict(fit17,newdata=test)
  diags&lt;-mean((test$fourteener-yhat)^2)
}
mean(diags)</code></pre>
<pre><code>## [1] 1.242867e-31</code></pre>
<pre class="r"><code>y&lt;-data.matrix(df$fourteener)
x&lt;-df%&gt;%dplyr::select(-fourteener)%&gt;%data.matrix()
cv&lt;-cv.glmnet(x,y, family=&quot;binomial&quot;)
lasso1&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso1)</code></pre>
<pre><code>## 16 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##               s0
## (Intercept)    .
## ID             0
## Lat            .
## Long           .
## Elevation_ft   .
## Prominence_ft  .
## Isolation_mi   .
## Distance_mi    .
## Ele_Gain_ft    .
## Low            .
## High           .
## Distance_c     .
## predictor      .
## prob           .
## logit.         .
## fourteener.    .</code></pre>
<pre class="r"><code>set.seed(1234)
k=5
data1&lt;-df[sample(nrow(df)),]
folds&lt;-cut(seq(1:nrow(df)),breaks=k,labels=F)
diags&lt;-NULL
for(i in 1:k){
  train&lt;-data1[folds!=i,]
  test&lt;-data1[folds==i,]
  fit&lt;-lm(fourteener~ID+Long+Elevation_ft+Prominence_ft+Distance_mi,data=train)
  yhat&lt;-predict(fit,newdata=test)
  diags&lt;-mean((test$fourteener-yhat)^2)
}
mean(diags)</code></pre>
<pre><code>## [1] 0.006044856</code></pre>
<p><em>According to our Lasso regression the variables which are the most important predictors of whether a mountain is classified as a fourteener of not include the Mountain ID, the Longitude, the Elevation in feet, the prominence in feet, and the Distance of the trail in miles. This makes sense as the fourteeners are classified based on elevation, prominence and isolation. They must be independent peaks, which depends on isolation and prominence. The RMSE of the new CV is 0.04101137, suggesting a much smaller margin of error than the accuracy predicted in question 5. The CV using only variables that proved to effect whether the mountain is a fourteener or not from lasso was much more accurate at predicting a fourteener than when all the variables were used to predict it.</em></p>
<div id="guidelines-and-rubric" class="section level2">
<h2>Guidelines and Rubric</h2>
<ul>
<li><p><strong>0. (5 pts)</strong> Introduce your dataset and each of your variables (or just your main variables if you have lots) in a paragraph.</p></li>
<li><p><strong>1. (15 pts)</strong> Perform a MANOVA testing whether any of your numeric variables (or a subset of them, if including them all doesn’t make sense) show a mean difference across levels of one of your categorical variables (3). If they do, perform univariate ANOVAs to find response(s) showing a mean difference across groups (3), and perform post-hoc t tests to find which groups differ (3). Discuss the number of tests you have performed, calculate the probability of at least one type I error (if unadjusted), and adjust the significance level accordingly (bonferroni correction) before discussing significant differences (3). Briefly discuss assumptions and whether or not they are likely to have been met (2).</p></li>
<li><p><strong>2. (10 pts)</strong> Perform some kind of randomization test on your data (that makes sense). This can be anything you want! State null and alternative hypotheses, perform the test, and interpret the results (7). Create a plot visualizing the null distribution and the test statistic (3).</p></li>
<li><p><strong>3. (35 pts)</strong> Build a linear regression model predicting one of your response variables from at least 2 other variables, including their interaction. Mean-center any numeric variables involved in the interaction.</p>
<ul>
<li>Interpret the coefficient estimates (do not discuss significance) (10)</li>
<li>Plot the regression using <code>ggplot()</code>. If your interaction is numeric by numeric, refer to code near the end of WS15 to make the plot. If you have 3 or more predictors, just chose two to plot for convenience. (7)</li>
<li>Check assumptions of linearity, normality, and homoskedasticity either graphically or using a hypothesis test (3)</li>
<li>Regardless, recompute regression results with robust standard errors via <code>coeftest(..., vcov=vcovHC(...))</code>. Discuss significance of results, including any changes from before/after robust SEs if applicable. (7)</li>
<li>What proportion of the variation in the outcome does your model explain? (3)</li>
<li>Finally, rerun the regression but without interactions (just main effects); compare this with the interaction model and the null model using a likelihood ratio test (4)</li>
</ul></li>
<li><p><strong>4. (5 pts)</strong> Rerun same regression model (with interaction), but this time compute bootstrapped standard errors. Discuss any changes you observe in SEs and p-values using these SEs compared to the original SEs and the robust SEs)</p></li>
<li><p><strong>5. (40 pts)</strong> Perform a logistic regression predicting a binary categorical variable (if you don’t have one, make/get one) from at least two explanatory variables (interaction not necessary).</p>
<ul>
<li>Interpret coefficient estimates in context (10)</li>
<li>Report a confusion matrix for your logistic regression (2)</li>
<li>Compute and discuss the Accuracy, Sensitivity (TPR), Specificity (TNR), and Recall (PPV) of your model (5)</li>
<li>Using ggplot, plot density of log-odds (logit) by your binary outcome variable (3)</li>
<li>Generate an ROC curve (plot) and calculate AUC (either manually or with a package); interpret (10)</li>
<li>Perform 10-fold (or repeated random sub-sampling) CV and report average out-of-sample Accuracy, Sensitivity, and Recall (10)</li>
</ul></li>
<li><p><strong>6. (10 pts)</strong> Choose one variable you want to predict (can be one you used from before; either binary or continuous) and run a LASSO regression inputting all the rest of your variables as predictors. Choose lambda to give the simplest model whose accuracy is near that of the best (i.e., <code>lambda.1se</code>). Discuss which variables are retained. Perform 10-fold CV using this model: if response in binary, compare model’s out-of-sample accuracy to that of your logistic regression in part 5; if response is numeric, compare the residual standard error (at the bottom of the summary output, aka RMSE): lower is better fit!</p></li>
</ul>
</div>
<div id="where-do-i-find-data-again" class="section level2">
<h2>Where do I find data again?</h2>
<p>You can choose ANY datasets you want that meet the above criteria for variables and observations. You can make it as serious as you want, or not, but keep in mind that you will be incorporating this project into a portfolio webpage for your final in this course, so choose something that really reflects who you are, or something that you feel will advance you in the direction you hope to move career-wise, or something that you think is really neat, or whatever. On the flip side, regardless of what you pick, you will be performing all the same tasks, so it doesn’t end up being that big of a deal.</p>
<p>If you are totally clueless and have no direction at all, log into the server and type</p>
<pre class="r"><code>data(package = .packages(all.available = TRUE))</code></pre>
<p>This will print out a list of <strong>ALL datasets in ALL packages</strong> installed on the server (a ton)! Scroll until your eyes bleed! Actually, do not scroll that much… To start with something more manageable, just run the command on your own computer, or just run <code>data()</code> to bring up the datasets in your current environment. To read more about a dataset, do <code>?packagename::datasetname</code>.</p>
<p>If it is easier for you, and in case you don’t have many packages installed, a list of R datasets from a few common packages (also downloadable in CSV format) is given at the following website: <a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>.</p>
<ul>
<li><p>A good package to download for fun/relevant data is <code>fivethiryeight</code>. Run <code>install.packages(&quot;fivethirtyeight&quot;),</code> load the packages with <code>library(fivethirtyeight)</code>, run <code>data()</code>, and then scroll down to view the datasets. Here is an online list of all 127 datasets (with links to the 538 articles). Lots of sports, politics, current events, etc.</p></li>
<li><p>If you have already started to specialize (e.g., ecology, epidemiology) you might look at discipline-specific R packages (vegan, epi, respectively). We will be using some tools from these packages later in the course, but they come with lots of data too, which you can explore according to the directions above</p></li>
<li><p>However, you <em>emphatically DO NOT</em> have to use datasets available via R packages! In fact, I would much prefer it if you found the data from completely separate sources and brought them together (a much more realistic experience in the real world)! You can even reuse data from your SDS328M project, provided it shares a variable in common with other data which allows you to merge the two together (e.g., if you still had the timestamp, you could look up the weather that day: <a href="https://www.wunderground.com/history/" class="uri">https://www.wunderground.com/history/</a>). If you work in a research lab or have access to old data, you could potentially merge it with new data from your lab!</p></li>
<li><p>Here is a curated list of interesting datasets (read-only spreadsheet format): <a href="https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit" class="uri">https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit</a></p></li>
<li><p>Here is another great compilation of datasets: <a href="https://github.com/rfordatascience/tidytuesday" class="uri">https://github.com/rfordatascience/tidytuesday</a></p></li>
<li><p>Here is the UCI Machine Learning Repository: <a href="https://archive.ics.uci.edu/ml/index.php" class="uri">https://archive.ics.uci.edu/ml/index.php</a></p>
<ul>
<li>See also <a href="https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data" class="uri">https://en.wikipedia.org/wiki/List_of_datasets_for_machine-learning_research#Biological_data</a></li>
</ul></li>
<li><p>Here is another good general place to look: <a href="https://www.kaggle.com/datasets" class="uri">https://www.kaggle.com/datasets</a></p></li>
<li><p>To help narrow your search down or to see interesting variable ideas, check out <a href="https://www.tylervigen.com/spurious-correlations" class="uri">https://www.tylervigen.com/spurious-correlations</a>. This is the spurious correlations website, and it is fun, but if you look at the bottom of each plot you will see sources for the data. This is a good place to find very general data (or at least get a sense of where you can scrape data together from)!</p></li>
<li><p>If you are interested in medical data, check out www.countyhealthrankings.org</p></li>
<li><p>If you are interested in scraping UT data, they make <em>loads</em> of data public (e.g., beyond just professor CVs and syllabi). Check out all the data that is available in the statistical handbooks: <a href="https://reports.utexas.edu/statistical-handbook" class="uri">https://reports.utexas.edu/statistical-handbook</a></p></li>
</ul>
<div id="broader-data-sources" class="section level5">
<h5>Broader data sources:</h5>
<p><a href="www.data.gov">Data.gov</a> 186,000+ datasets!</p>
<p><a href="Social%20Explorer">Social Explorer</a> is a nice interface to Census and American Community Survey data (more user-friendly than the government sites). May need to sign up for a free trial.</p>
<p><a href="www.bls.gov">U.S. Bureau of Labor Statistics</a></p>
<p><a href="www.census.gov">U.S. Census Bureau</a></p>
<p><a href="www.gapminder.org/data">Gapminder</a>, data about the world.</p>
<p>…</p>
</div>
</div>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
