---
title: "Resume"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Jade Anderson's Resume


  Hi! I'm a third year Biology and Sustainability Studies student at the University of Texas at Austin.

  I love spending time outside, making art, perusing vintage stores, and learning about science! 

  I spent this past semester (Fall 2019) learning RStudio and familiarizing myself with Python! If you navigate to the Projects tab of this website you can see some of the work I am most proud of!

  From July 2019 to December 2019, I interned at the environmental non-profit Devils River Conservancy as a Database Developer!

  Some of my duties as a database developer included:

    Executing a project focused on sweeping, reviewing, and 
    compiling over 600 journal articles, legislative bills,
    historic archives and other documents regarding the
    Devils River into a Zotero database
    
    Assisting the Executive Director in grant research 
    and proposal
    
    Attending a research based trip to Del Rio, Texas in 
    order to search for historic documents related to 
    the Devils River
  
  
  
Some other work endeavors and extracurriculars I've been apart of include,

  Team Leader at Next Level Burger from October 2018 - Present

    Serves as front of house for the restaurant, 
    explaining our concept and fielding 
    questions from customers
    
    Manages multiple stations at once, displaying
    multitasking & time management skills
    
    Received a promotion, which includes the added
    responsibility of balancing the register at the
    close of the business day
    
    
    
  Member of the Campus Environmental Center from Fall 2018 - Present

    Led volunteer groups in building and managing
    the CEC’s Microfarm project 
    
    Assisted in moving and setting up the 100% 
    student run sustainable organic farm to its
    new half acre site



  Member of Alpha Kapa Psi Business Fraternity from Spring 2018 - Present

    Learned practical, professional skills such as
    resume building, interview skills, and 
    networking opportunities
    
    Organized and fundraised for specific goals within
    certain timelines
    
    Participated in Case Competitions at a competitive level



  Researcher for the Freshman Research Initiative: Vertebrate Interactome Mapping Lab during Spring 2018

    Researched the unknown mechanisms and functions of
    GPATCH3 unmutated
    
    Worked independently, kept lab journal, learned valuable
    laboratory skills and received proper laboratory certifications
    



